### PR TITLE
Upgrade to go v1.13.1

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by chenrui333** [comment]
Looks like the vendor folder is not the in the repo, adding it now.

**Comment by chenrui333** [comment]
```
$ make test
==> Checking that code complies with gofmt requirements...
go generate ./...
go: finding golang.org/x/tools v0.0.0-20190628153133-6cdbf07be9d0
go test ./...
go: finding github.com/hashicorp/yamux v0.0.0-20181012175058-2f1d1f20f75d
go: finding github.com/go-test/deep v1.0.3
go: finding github.com/apparentlymart/go-dump v0.0.0-20180507223929-23540a00eaa3
ok  	github.com/hashicorp/terraform-plugin-sdk/helper/acctest	0.775s
ok  	github.com/hashicorp/terraform-plugin-sdk/helper/customdiff	0.337s
?   	github.com/hashicorp/terraform-plugin-sdk/helper/encryption	[no test files]
ok  	github.com/hashicorp/terraform-plugin-sdk/helper/hashcode	0.322s
?   	github.com/hashicorp/terraform-plugin-sdk/helper/logging	[no test files]
ok  	github.com/hashicorp/terraform-plugin-sdk/helper/mutexkv	0.321s
ok  	github.com/hashicorp/terraform-plugin-sdk/helper/pathorcontents	0.358s
ok  	github.com/hashicorp/terraform-plugin-sdk/helper/resource	2.972s
ok  	github.com/hashicorp/terraform-plugin-sdk/helper/schema	0.453s
ok  	github.com/hashicorp/terraform-plugin-sdk/helper/structure	0.315s
ok  	github.com/hashicorp/terraform-plugin-sdk/helper/validation	0.321s
ok  	github.com/hashicorp/terraform-plugin-sdk/httpclient	0.351s
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/addrs	0.159s
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/command/format	2.609s
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/configs	2.596s
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/configs/configload	0.412s
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/configs/configschema	3.170s
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/configs/hcl2shim	0.505s
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/dag	1.694s
?   	github.com/hashicorp/terraform-plugin-sdk/internal/earlyconfig	[no test files]
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/flatmap	0.453s
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/helper/config	0.403s
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/helper/didyoumean	0.234s
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/helper/experiment	4.079s
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin	2.522s
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/httpclient	0.174s
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/initwd	0.761s
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/lang	2.405s
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/lang/blocktoattr	3.037s
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/lang/funcs	2.641s
?   	github.com/hashicorp/terraform-plugin-sdk/internal/modsdir	[no test files]
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/moduledeps	0.495s
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/plans	0.233s
?   	github.com/hashicorp/terraform-plugin-sdk/internal/plans/internal/planproto	[no test files]
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/plans/objchange	0.275s
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/plans/planfile	0.241s
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/plugin/convert	2.797s
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/plugin/discovery	2.533s
?   	github.com/hashicorp/terraform-plugin-sdk/internal/plugin/mock_proto	[no test files]
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/providers	0.537s
?   	github.com/hashicorp/terraform-plugin-sdk/internal/provisioners	[no test files]
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/registry	0.632s
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/registry/regsrc	2.344s
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/registry/response	2.328s
?   	github.com/hashicorp/terraform-plugin-sdk/internal/registry/test	[no test files]
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/states	0.459s
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/states/statefile	0.300s
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/svchost	0.369s
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/svchost/auth	3.635s
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/svchost/disco	0.349s
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/tfdiags	0.339s
?   	github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5	[no test files]
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/vault/helper/pgpkeys	1.673s
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/vault/sdk/helper/compressutil	0.676s
ok  	github.com/hashicorp/terraform-plugin-sdk/internal/vault/sdk/helper/jsonutil	0.430s
?   	github.com/hashicorp/terraform-plugin-sdk/internal/version	[no test files]
?   	github.com/hashicorp/terraform-plugin-sdk/meta	[no test files]
ok  	github.com/hashicorp/terraform-plugin-sdk/plugin	0.261s
ok  	github.com/hashicorp/terraform-plugin-sdk/terraform	6.459s
```

**Comment by chenrui333** [comment]
The CI changes seems did not get kicked off.

**Comment by radeksimko** [comment]
Hi @chenrui333 
thank you for your PR.

Unfortunately we need to clean up some technical debt before we can upgrade.
I would therefore suggest closing this PR for the time being as this process may take time and it's likely that there will be other PRs which touch the same code and cause conflicts with your PR, rendering it unmergeable.

We are working to ensure that no Terraform providers depend on each other and/or that providers comply with the import path conventions which apply to any `>v1` modules.

This is important before we force-upgrade all providers to Go 1.13 (which is effectively what this PR does since all providers have to consume this SDK). Go 1.13 introduces much stricter rules on "importability" of such modules. It is possible to import such noncompliant modules in 1.12, albeit with `+incompatible` suffix.

**Comment by radeksimko** [comment]
I'm going to close this PR for now, for the reasons mentioned above, I'm happy to review a fresh PR when we are ready for the upgrade though.

Thank you for the time you invested in the contribution.

**Comment by chenrui333** [comment]
Totally cool with me. Thanks!

**Pull request closed without merging**
