### PR TITLE
Fix HasChange when using nested schema.Set

### LINKED ISSUE #361: HasChange wrongly returns TRUE on nested shema.Set structures
### SDK version

```
v1.7.0
```

### Relevant provider source code

When investigating [Terraform AWS provider issue #11059](https://github.com/terraform-providers/terraform-provider-aws/issues/11059) I came across some cases where nested schema.Set structures as the one [mentioned in the 2nd part of this entry](https://github.com/terraform-providers/terraform-provider-aws/issues/11059#issuecomment-599631533) produce unnecessary calls later down in the code

```go
...
```

### Terraform Configuration Files

```hcl
...
```

### Expected Behavior

HasChange should return false as entries are perfectly equivalent

### Actual Behavior

[This test](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_security_group.go#L695) returns true because
of reflect.DeepEqual which returns false when traversing Func(s)

### Steps to Reproduce

See aforementioned issue

### References

- [Terraform AWS provider issue #11059](https://github.com/terraform-providers/terraform-provider-aws/issues/11059)
- [The code I have implemented which prevents this](https://github.com/hashicorp/terraform-plugin-sdk/compare/master...obourdon:master)

### PR DESCRIPTION
**Pull request by obourdon**
This fixes #361

### CODE REVIEW

**Comment by paultyng** [comment]
@obourdon this seems like a reasonable fix, do you mind adding some testing around the issue to demonstrate the problems (and prevent regression)?

Is it possible the AWS code should be modified to use `HashEqual` instead? Currently the way the SDK does most set handling is via the hash, this is changing a bit in 0.12 but will probably remain this way in this version of the SDK for the time being.

**Comment by obourdon** [comment]
@paultyng many thanks for the comments above. Will definitely look into putting some tests and also have a look at your suggestion about AWS HashEqual. I just fixed the formatting as I did not see that the CI had failed. Many thanks again

**Comment by paultyng** [comment]
The more I thought about this, I think this approach to `Equal` is your best bet, as `HasChange` has different mean than the set hashing which is mostly about matching up values for diffing. Will have someone take a peek, but we'll need some test coverage to merge.

**Comment by obourdon** [comment]
@paultyng test has been added and I have verified that reverting commit 
48bd90d fails and succeed otherwise running:
```
go test ./... -run 'TestSet.*' -count=1
```

**Comment by obourdon** [comment]
@appilon no pb at all, just let me know if you need me for anything.

**Pull request merged**
