### PR TITLE
pass original config value as the Raw field of resourceConfig

### PR DESCRIPTION
**Pull request by mingfang**
Some providers require the original config to work properly.
This PR is the minimum changes needed to pass the original config as the Raw field of the resourceConfig when calling the provider's  `customizeDiff` callback function.  Since the Raw field was not used for any other purpose I think this is safe.  The semantics always is meaningful since Raw is now the original config and the Config field has the proposed new config.
Related to https://github.com/hashicorp/terraform/issues/20327

### CODE REVIEW

**Comment by kmoe** [comment]
Thanks for the PR, @mingfang. We're looking into this at the moment.

**Comment by mingfang** [comment]
@kmoe 
This is how I use the raw values 
https://github.com/mingfang/terraform-provider-k8s/blob/master/k8s/tf2k8s_visitor.go#L218

**Comment by paultyng** [comment]
Now that [0.11 support in providers is deprecated](https://www.hashicorp.com/blog/deprecating-terraform-0-11-support-in-terraform-providers/) we will be starting to remove those code paths as part of a `v2` release of the SDK to allow us to start taking advantage of a number of new features in Terraform 0.12. Cleaner explicit access to prior state, proposed state, and config values are one of the first new features we will be adding.

Thanks a lot for your work on this, we definitely agree its functionality we need to support, but we can take a much cleaner approach if we just focus on protocol 5.0. We'll be tracking that work in #133.

**Comment by mingfang** [comment]
@paultyng Thanks for looking into this. I agree that focusing on v2 of sdk is the best approach.

**Pull request closed without merging**
