### PR TITLE
Debug Flaky Tests

### PR DESCRIPTION
**Pull request by appilon**
These tests seem to heavily dependant on certain timings. Locally I have never had these tests fail (can't reproduce), strangely these tests never failed in master. There has to be something around the amount of tests (which has significantly been reduced in V2 from code deletion) which leads to CircleCI perhaps running this on more limited hardware, where the carefully setup timing doesn't pass (refreshes running slower, sleep/wake happening off-schedule? 🤷‍♂)

The tests don't consistently fail so best I can do is start the debugging process.

### CODE REVIEW

**Comment by paultyng** [comment]
Have you looked at GOMAXPROCS? Maybe just have this test log it before running?

**Comment by appilon** [comment]
tests passing of course 😑 . @paultyng can we merge the log and I'll investigate the next time it fails

**Comment by appilon** [comment]
I must not totally understand our circle setup, but the tests did fail for the "release" workflow (I'm not sure why that runs on every PR, might have been the only way to get Circle to do the things we want). `inconsistent_negative` failed with the following output:
```
=== RUN   TestWaitForState_inconsistent_negative
2020/02/06 00:33:51 [DEBUG] Waiting for state to become: [done]
2020/02/06 00:33:51 [TRACE] Waiting 10ms before next try
2020/02/06 00:33:51 [TRACE] Waiting 10ms before next try
2020/02/06 00:33:51 [TRACE] Waiting 10ms before next try
2020/02/06 00:33:51 [TRACE] Waiting 10ms before next try
2020/02/06 00:33:51 [TRACE] Waiting 10ms before next try
2020/02/06 00:33:51 [TRACE] Waiting 10ms before next try
2020/02/06 00:33:51 [TRACE] Waiting 10ms before next try
2020/02/06 00:33:51 [TRACE] Waiting 10ms before next try
2020/02/06 00:33:51 [TRACE] Waiting 10ms before next try
--- FAIL: TestWaitForState_inconsistent_negative (0.09s)
    state_test.go:117: GOMAXPROCS=36
    state_test.go:150: error prefix doesn't match.
        Expected: "timeout while waiting for state to become 'done'"
        Given: "No more states available"
```
Clearly enough processes... The other aspect of the environment is the tests are run via a different runner
```
gotestsum --junitfile /tmp/test-results/report/gotestsum-report.xml -- -coverprofile=cover.out ./...
```
I will see if I can use this locally to repro the issue.

**Comment by appilon** [comment]
The problem seems to have "gone away" on its own... for now

**Pull request closed without merging**
