### PR TITLE
Fix warnings around errors

### PR DESCRIPTION
**Pull request by abergmeier**
Use correct function and remove ending exclamation mark.

### CODE REVIEW

**Comment by paddycarver** [comment]
Hey @abergmeier, does this fix a behavior or does something not work without this merged that works with it merged?

**Comment by abergmeier** [comment]
It fixes warning you get from Go. So reducing the noise when coding. Wonder though, why your CI doesn't flag that.

**Comment by paddycarver** [comment]
Hmm, as far as I know, Go doesn't issue warnings. Do you mean `golint`? Or `go vet`? What command are you running that's producing the warning?

**Comment by abergmeier** [comment]
It is actually both. IIRC exclamation mark is `golint`, formatting function is `go vet`.

**Review by paddycarver — APPROVED** [review]

**Pull request merged**
