### PR TITLE
website: Add highlight callout for migrating to terraform-plugin-testing

### PR DESCRIPTION
**Pull request by bflad**
Reference: https://discuss.hashicorp.com/t/announcing-the-terraform-plugin-testing-module/49914

This renders as an informational callout at the top of each of the existing SDKv2 testing pages to encourage migrating to the new testing module.

Screenshot 2023-02-14 at 4 43 06 PM

### CODE REVIEW

**Review by austinvalle — APPROVED** [review]
overall LGTM, do we want to update the best practices page as well?

https://developer.hashicorp.com/terraform/plugin/sdkv2/best-practices/testing

**Comment by bflad** [comment]
I think these "best practices" pages in general will need an overhaul as less and less folks will be browsing the terraform-plugin-sdk documentation. In particular for the testing page this could be:

- Creating similar content in the terraform-plugin-testing website
- Removing the page in this website
- Updating the side navigation to point to the new page
- Setting up a website redirect for the old page to the new page

I'm not sure if its worth trying to get this all done right now though or make a more concerted effort with the whole section of pages and deciding where they will live.

**Review by bendbennett — APPROVED** [review]
LGTM 👍

**Comment by bflad** [comment]
Created https://github.com/hashicorp/terraform-plugin-sdk/issues/1151 for follow up.

**Pull request merged**
