### PR TITLE
schema: discard function fields for json marshalling

### PR DESCRIPTION
**Pull request by sylr**
Useful for debugging.

### CODE REVIEW

**Comment by paultyng** [comment]
These types are not meant for marshaling, if you want to marshal in your own codebase you can copy the types to a type special cased for that purpose. The method we use currently for extracting schema to JSON is to execute the [`terraform providers schema` command](https://www.terraform.io/docs/commands/providers/schema.html).

**Comment by sylr** [comment]
Like I said, it was for debugging:

```go
	j, err := json.MarshalIndent(result, "", "  ")
	log.Printf("[DEBUG] before sortSecurityRules sorting: %v (err: %v)", string(j), err)
	sortSecurityRules(result)
	j2, err := json.MarshalIndent(result, "", "  ")
	log.Printf("[DEBUG] after sortSecurityRules sorting: %v (err: %v)", string(j2), err)
```

**Comment by paultyng** [comment]
I know what you are getting at, but dynamic schema itself is problematic for Terraform, if you are generating your schema to the point you need to debug it, you are probably going to run in to additional problems down the line (state migrations, etc). 

If you really want debugging of schema in your code, its more tedious, but you could wrap it in an anonymous struct to override like:

```go
	x := (struct {
		Type schema.ValueType
		ConfigMode schema.SchemaConfigMode
		Optional bool
		Required bool
		DiffSuppressFunc schema.SchemaDiffSuppressFunc `json:"-"`
		Default     interface{}
		DefaultFunc schema.SchemaDefaultFunc `json:"-"`
		Description string
		InputDefault string
		Computed  bool
		ForceNew  bool
		StateFunc schema.SchemaStateFunc `json:"-"`
		Elem interface{}
		MaxItems int
		MinItems int
		PromoteSingle bool
		Set schema.SchemaSetFunc `json:"-"`
		ComputedWhen []string
		ConflictsWith []string
		ExactlyOneOf  []string
		AtLeastOneOf  []string
		Deprecated string
		Removed string
		ValidateFunc schema.SchemaValidateFunc `json:"-"`
		Sensitive bool
	})(result)
```

**Comment by sylr** [comment]
Well, that's the thing, I'm not debugging my schema but someone else's.

**Pull request closed without merging**
